/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package tel.cjs.tomorrowreader;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int background=0x7f050000;
        public static final int cache_color_hint=0x7f05000f;
        public static final int dark_button_text_color=0x7f050003;
        public static final int dark_button_text_shadow=0x7f050004;
        public static final int list_divider=0x7f05000c;
        public static final int list_item_gradient_end=0x7f050009;
        public static final int list_item_gradient_start=0x7f050008;
        public static final int list_item_text_shadow=0x7f05000a;
        public static final int list_text_color=0x7f050007;
        public static final int list_text_shadow=0x7f05000b;
        public static final int reader_background=0x7f05000e;
        public static final int reader_text_color=0x7f05000d;
        public static final int text=0x7f050001;
        public static final int text_shadow=0x7f050002;
        public static final int top_bar_color=0x7f050005;
        public static final int top_bar_shadow=0x7f050006;
    }
    public static final class drawable {
        public static final int btn=0x7f020000;
        public static final int btn_disabled=0x7f020001;
        public static final int btn_pressed=0x7f020002;
        public static final int dark_button=0x7f020003;
        public static final int gear=0x7f020004;
        public static final int icon_add=0x7f020005;
        public static final int icon_arrow=0x7f020006;
        public static final int icon_delete=0x7f020007;
        public static final int icon_home=0x7f020008;
        public static final int icon_original=0x7f020009;
        public static final int icon_preferences=0x7f02000a;
        public static final int icon_refresh=0x7f02000b;
        public static final int icon_return=0x7f02000c;
        public static final int icon_text=0x7f02000d;
        public static final int list_background=0x7f02000e;
        public static final int list_background_pressed=0x7f02000f;
        public static final int list_item_selector=0x7f020010;
        public static final int list_selector=0x7f020011;
        public static final int loading_window=0x7f020012;
        public static final int logo=0x7f020013;
        public static final int logo_a=0x7f020014;
        public static final int logo_small=0x7f020015;
        public static final int refresh=0x7f020016;
        public static final int separator=0x7f020017;
        public static final int top_button=0x7f020018;
        public static final int topbar=0x7f020019;
        public static final int topbar_pressed=0x7f02001a;
    }
    public static final class id {
        public static final int TextView01=0x7f090004;
        public static final int add_button=0x7f090007;
        public static final int bookmark_content=0x7f090013;
        public static final int delete_button=0x7f090011;
        public static final int field_email=0x7f090015;
        public static final int field_password=0x7f090017;
        public static final int field_url=0x7f090001;
        public static final int home_button=0x7f09000d;
        public static final int label_email=0x7f090014;
        public static final int label_password=0x7f090016;
        public static final int label_url=0x7f090000;
        public static final int login_submit_button=0x7f090018;
        public static final int logo=0x7f090009;
        public static final int main_signin_button=0x7f09000b;
        public static final int menu_delete=0x7f09001a;
        public static final int menu_goto=0x7f090019;
        public static final int original_button=0x7f09000f;
        public static final int refresh_button=0x7f090005;
        public static final int registration_button=0x7f09000c;
        public static final int separator_b1=0x7f090006;
        public static final int separator_b2=0x7f090008;
        public static final int separator_r1=0x7f09000e;
        public static final int separator_r3=0x7f090010;
        public static final int separator_r4=0x7f090012;
        public static final int signin_as_button=0x7f09000a;
        public static final int submit_button=0x7f090002;
        public static final int title=0x7f090003;
    }
    public static final class layout {
        public static final int add_dialog=0x7f030000;
        public static final int bookmark_row=0x7f030001;
        public static final int bookmarks=0x7f030002;
        public static final int main=0x7f030003;
        public static final int reader=0x7f030004;
        public static final int sign_in=0x7f030005;
    }
    public static final class menu {
        public static final int bookmarks_menu=0x7f080000;
        public static final int reader_menu=0x7f080001;
    }
    public static final class string {
        public static final int add_bookmark_label=0x7f060004;
        public static final int app_name=0x7f060000;
        public static final int auth_error=0x7f06000c;
        public static final int bookmarks_label=0x7f060015;
        public static final int bookmarks_manager_title=0x7f060008;
        public static final int cancel=0x7f060012;
        public static final int delete=0x7f060011;
        public static final int delete_confirmation=0x7f060013;
        public static final int deleted=0x7f060014;
        public static final int email_field_label=0x7f060002;
        public static final int goto_original=0x7f060010;
        public static final int password_field_label=0x7f060003;
        public static final int preferences_auto_sync=0x7f06000f;
        public static final int reader_title=0x7f060009;
        public static final int registration=0x7f06000b;
        public static final int registration_url=0x7f060001;
        public static final int sign_in=0x7f06000a;
        public static final int signin_button_label=0x7f060005;
        public static final int signin_title=0x7f060007;
        public static final int sync_in_progress=0x7f06000e;
        public static final int updated=0x7f06000d;
        public static final int url_field_label=0x7f060006;
    }
    public static final class style {
        public static final int BookmarksListItem=0x7f07000b;
        /** <item name="android:shadowColor">@color/list_text_shadow</item>
    <item name="android:shadowDx">0</item>
    <item name="android:shadowDy">1</item>
    <item name="android:shadowRadius">1</item>
<item name="android:listSelector">@drawable/list_selector</item>
         */
        public static final int BookmarksListTextView=0x7f07000c;
        /**  List 
<item name="android:listSelector">@drawable/list_selector</item>     
         */
        public static final int BookmarksListView=0x7f07000a;
        /** Main Window
         */
        public static final int DarkButton=0x7f070002;
        public static final int DefaultTextAppearance=0x7f070001;
        public static final int DefaultTheme=0x7f070000;
        public static final int FastSigninButton=0x7f070004;
        public static final int MainButton=0x7f070003;
        /** Reader
         */
        public static final int Reader=0x7f07000d;
        /** Signin
         */
        public static final int TextViewShadowed=0x7f070005;
        public static final int TopBarButton=0x7f070008;
        /**  TopBar 
         */
        public static final int TopBarLayout=0x7f070006;
        public static final int TopBarSeparator=0x7f070007;
        public static final int TopBarTextView=0x7f070009;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
    }
}
