/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package tel.cjs.tomorrowreader;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int button_login=0x7f040004;
        public static final int field_email=0x7f040001;
        public static final int field_password=0x7f040003;
        public static final int label_email=0x7f040000;
        public static final int label_password=0x7f040002;
    }
    public static final class layout {
        public static final int login=0x7f020000;
    }
    public static final class string {
        public static final int app_name=0x7f030000;
        public static final int login_email_label=0x7f030001;
        public static final int login_password_label=0x7f030002;
    }
}
